# Generated by Django 6.0.8 on 2026-09-10 18:06

from django.db import migrations, models


def mark_legacy_attempts(apps, schema_editor):
    # Never reconstruct an old exam from today's mutable question pointers.
    Attempt = apps.get_model("core", "Attempt")
    Attempt.objects.using(schema_editor.connection.alias).update(snapshot_origin="legacy_unverified")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='frozen_definition',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='attempt',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='result_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='attempt',
            name='snapshot_origin',
            field=models.CharField(choices=[('pending', 'Captura pendente'), ('creation', 'Capturado na criação'), ('deferred', 'Capturado na primeira ação'), ('legacy_unverified', 'Histórico não comprovado')], default='pending', max_length=32),
        ),
        migrations.RunPython(mark_legacy_attempts, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['owner', 'status', '-started_at'], name='attempt_owner_status_started'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('owner', 'idempotency_key'), name='unique_attempt_owner_request'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='attempt_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'submitted', 'graded', 'abandoned'])), name='attempt_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), ('submitted_at__isnull', True), _connector='OR'), name='active_attempt_not_submitted'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.CheckConstraint(condition=models.Q(('answer_version__gte', 1)), name='attempt_answer_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='attemptcheckpoint',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='attempt_checkpoint_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='simulation',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 1), ('duration_minutes__lte', 1440)), name='simulation_duration_range'),
        ),
        migrations.AddConstraint(
            model_name='simulation',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ['formal', 'training', 'free'])), name='simulation_valid_mode'),
        ),
    ]

