"""Frozen foundational grants and a non-human tool identity; no passwords seeded."""
import uuid
from django.db import migrations

MACHINE_ID = uuid.uuid5(uuid.NAMESPACE_URL, "https://kairos.2-24-215-183.sslip.io/services/tool-client")
ROLES = {'administrador': ['ai.approve',
                   'ai.consult',
                   'ai.create',
                   'ai.delete',
                   'ai.edit',
                   'ai.manage',
                   'ai.publish',
                   'ai.read',
                   'ai.review',
                   'ai.use',
                   'audit.approve',
                   'audit.create',
                   'audit.delete',
                   'audit.edit',
                   'audit.manage',
                   'audit.publish',
                   'audit.read',
                   'audit.review',
                   'case.approve',
                   'case.create',
                   'case.delete',
                   'case.edit',
                   'case.manage',
                   'case.publish',
                   'case.read',
                   'case.review',
                   'content.approve',
                   'content.create',
                   'content.delete',
                   'content.edit',
                   'content.manage',
                   'content.publish',
                   'content.read',
                   'content.review',
                   'corpus.approve',
                   'corpus.create',
                   'corpus.curate',
                   'corpus.delete',
                   'corpus.edit',
                   'corpus.manage',
                   'corpus.publish',
                   'corpus.read',
                   'corpus.review',
                   'corpus.update',
                   'exam.approve',
                   'exam.create',
                   'exam.delete',
                   'exam.edit',
                   'exam.manage',
                   'exam.publish',
                   'exam.read',
                   'exam.review',
                   'ingestion.approve',
                   'ingestion.create',
                   'ingestion.delete',
                   'ingestion.edit',
                   'ingestion.manage',
                   'ingestion.publish',
                   'ingestion.read',
                   'ingestion.review',
                   'legal.publish',
                   'legal.review',
                   'piece.approve',
                   'piece.create',
                   'piece.delete',
                   'piece.edit',
                   'piece.manage',
                   'piece.publish',
                   'piece.read',
                   'piece.review',
                   'prompt.approve',
                   'prompt.create',
                   'prompt.delete',
                   'prompt.edit',
                   'prompt.manage',
                   'prompt.publish',
                   'prompt.read',
                   'prompt.review',
                   'publication.approve',
                   'publication.create',
                   'publication.delete',
                   'publication.edit',
                   'publication.manage',
                   'publication.publish',
                   'publication.read',
                   'publication.review',
                   'question.approve',
                   'question.create',
                   'question.delete',
                   'question.edit',
                   'question.manage',
                   'question.publish',
                   'question.read',
                   'question.review',
                   'roles.approve',
                   'roles.create',
                   'roles.delete',
                   'roles.edit',
                   'roles.manage',
                   'roles.publish',
                   'roles.read',
                   'roles.review',
                   'rubric.approve',
                   'rubric.create',
                   'rubric.delete',
                   'rubric.edit',
                   'rubric.manage',
                   'rubric.publish',
                   'rubric.read',
                   'rubric.review',
                   'settings.approve',
                   'settings.create',
                   'settings.delete',
                   'settings.edit',
                   'settings.manage',
                   'settings.publish',
                   'settings.read',
                   'settings.review',
                   'simulation.approve',
                   'simulation.create',
                   'simulation.delete',
                   'simulation.edit',
                   'simulation.manage',
                   'simulation.publish',
                   'simulation.read',
                   'simulation.review',
                   'study.use',
                   'support.manage',
                   'teaching.manage',
                   'tool.approve',
                   'tool.create',
                   'tool.delete',
                   'tool.edit',
                   'tool.manage',
                   'tool.publish',
                   'tool.read',
                   'tool.review',
                   'users.approve',
                   'users.create',
                   'users.delete',
                   'users.edit',
                   'users.manage',
                   'users.publish',
                   'users.read',
                   'users.review'],
 'administrador-de-conteudo': ['audit.read',
                               'case.create',
                               'case.edit',
                               'case.read',
                               'content.create',
                               'content.edit',
                               'content.read',
                               'corpus.read',
                               'exam.create',
                               'exam.edit',
                               'exam.read',
                               'piece.create',
                               'piece.edit',
                               'piece.read',
                               'publication.publish',
                               'publication.read',
                               'question.create',
                               'question.edit',
                               'question.read',
                               'rubric.create',
                               'rubric.edit',
                               'rubric.read'],
 'aluno': ['ai.consult', 'ai.use', 'study.use'],
 'auditor': ['audit.read'],
 'conta-de-servico': ['mcp.query', 'service.integrate'],
 'curador': ['corpus.curate', 'corpus.read', 'corpus.update', 'legal.review'],
 'editor': ['case.create',
            'case.edit',
            'case.read',
            'content.create',
            'content.edit',
            'content.read',
            'exam.create',
            'exam.edit',
            'exam.read',
            'piece.create',
            'piece.edit',
            'piece.read',
            'question.create',
            'question.edit',
            'question.read',
            'rubric.create',
            'rubric.edit',
            'rubric.read'],
 'gestor-de-usuarios': ['audit.read', 'support.manage', 'users.manage', 'users.read'],
 'professor': ['ai.consult',
               'ai.use',
               'case.create',
               'case.edit',
               'case.read',
               'content.create',
               'content.edit',
               'content.read',
               'exam.create',
               'exam.edit',
               'exam.read',
               'piece.create',
               'piece.edit',
               'piece.read',
               'question.create',
               'question.edit',
               'question.read',
               'rubric.create',
               'rubric.edit',
               'rubric.read',
               'study.use',
               'teaching.manage'],
 'revisor-juridico': ['audit.read',
                      'case.approve',
                      'case.read',
                      'case.review',
                      'content.approve',
                      'content.read',
                      'content.review',
                      'corpus.approve',
                      'corpus.curate',
                      'corpus.read',
                      'corpus.review',
                      'corpus.update',
                      'exam.approve',
                      'exam.read',
                      'exam.review',
                      'legal.publish',
                      'legal.review',
                      'piece.approve',
                      'piece.read',
                      'piece.review',
                      'publication.approve',
                      'publication.publish',
                      'publication.read',
                      'publication.review',
                      'question.approve',
                      'question.read',
                      'question.review',
                      'rubric.approve',
                      'rubric.read',
                      'rubric.review'],
 'superadministrador': ['ai.approve',
                        'ai.consult',
                        'ai.create',
                        'ai.delete',
                        'ai.edit',
                        'ai.manage',
                        'ai.publish',
                        'ai.read',
                        'ai.review',
                        'ai.use',
                        'audit.approve',
                        'audit.create',
                        'audit.delete',
                        'audit.edit',
                        'audit.manage',
                        'audit.publish',
                        'audit.read',
                        'audit.review',
                        'case.approve',
                        'case.create',
                        'case.delete',
                        'case.edit',
                        'case.manage',
                        'case.publish',
                        'case.read',
                        'case.review',
                        'content.approve',
                        'content.create',
                        'content.delete',
                        'content.edit',
                        'content.manage',
                        'content.publish',
                        'content.read',
                        'content.review',
                        'corpus.approve',
                        'corpus.create',
                        'corpus.curate',
                        'corpus.delete',
                        'corpus.edit',
                        'corpus.manage',
                        'corpus.publish',
                        'corpus.read',
                        'corpus.review',
                        'corpus.update',
                        'exam.approve',
                        'exam.create',
                        'exam.delete',
                        'exam.edit',
                        'exam.manage',
                        'exam.publish',
                        'exam.read',
                        'exam.review',
                        'ingestion.approve',
                        'ingestion.create',
                        'ingestion.delete',
                        'ingestion.edit',
                        'ingestion.manage',
                        'ingestion.publish',
                        'ingestion.read',
                        'ingestion.review',
                        'legal.publish',
                        'legal.review',
                        'piece.approve',
                        'piece.create',
                        'piece.delete',
                        'piece.edit',
                        'piece.manage',
                        'piece.publish',
                        'piece.read',
                        'piece.review',
                        'prompt.approve',
                        'prompt.create',
                        'prompt.delete',
                        'prompt.edit',
                        'prompt.manage',
                        'prompt.publish',
                        'prompt.read',
                        'prompt.review',
                        'publication.approve',
                        'publication.create',
                        'publication.delete',
                        'publication.edit',
                        'publication.manage',
                        'publication.publish',
                        'publication.read',
                        'publication.review',
                        'question.approve',
                        'question.create',
                        'question.delete',
                        'question.edit',
                        'question.manage',
                        'question.publish',
                        'question.read',
                        'question.review',
                        'roles.approve',
                        'roles.create',
                        'roles.delete',
                        'roles.edit',
                        'roles.manage',
                        'roles.publish',
                        'roles.read',
                        'roles.review',
                        'rubric.approve',
                        'rubric.create',
                        'rubric.delete',
                        'rubric.edit',
                        'rubric.manage',
                        'rubric.publish',
                        'rubric.read',
                        'rubric.review',
                        'settings.approve',
                        'settings.create',
                        'settings.delete',
                        'settings.edit',
                        'settings.manage',
                        'settings.publish',
                        'settings.read',
                        'settings.review',
                        'simulation.approve',
                        'simulation.create',
                        'simulation.delete',
                        'simulation.edit',
                        'simulation.manage',
                        'simulation.publish',
                        'simulation.read',
                        'simulation.review',
                        'study.use',
                        'support.manage',
                        'teaching.manage',
                        'tool.approve',
                        'tool.create',
                        'tool.delete',
                        'tool.edit',
                        'tool.manage',
                        'tool.publish',
                        'tool.read',
                        'tool.review',
                        'users.approve',
                        'users.create',
                        'users.delete',
                        'users.edit',
                        'users.manage',
                        'users.publish',
                        'users.read',
                        'users.review'],
 'suporte': ['support.manage', 'users.read']}

def forwards(apps, schema_editor):
    alias = schema_editor.connection.alias
    Permission = apps.get_model("core", "Permission")
    Role = apps.get_model("core", "Role")
    User = apps.get_model("core", "User")
    UserRole = apps.get_model("core", "UserRole")
    permissions = {}
    for code in sorted({code for codes in ROLES.values() for code in codes}):
        permissions[code], _ = Permission.objects.using(alias).get_or_create(codename=code, defaults={"description": code})
    for slug, codes in ROLES.items():
        role, _ = Role.objects.using(alias).get_or_create(slug=slug, defaults={"name": slug.replace("-", " ").title(), "is_system": True})
        role.kairos_permissions.set([permissions[code] for code in codes])
    machine, created = User.objects.using(alias).get_or_create(id=MACHINE_ID, defaults={
        "username": "kairos_tool_client", "display_name": "Kairós tool client", "password": "!",
        "is_active": True, "is_staff": False, "is_superuser": False,
    })
    if not created and (machine.username != "kairos_tool_client" or machine.is_staff or machine.is_superuser or not machine.password.startswith("!")):
        raise RuntimeError("Machine identity conflicts with an existing account")
    User.objects.using(alias).filter(id=MACHINE_ID).update(is_active=True)
    role = Role.objects.using(alias).get(slug="conta-de-servico")
    UserRole.objects.using(alias).get_or_create(user=machine, role=role)

def backwards(apps, schema_editor):
    # Do not restore historical broad grants automatically during a rollback.
    # Human assignments survive; the pre-release encrypted DB backup is the
    # authoritative rollback for its exact historical authorization matrix.
    alias = schema_editor.connection.alias
    User = apps.get_model("core", "User")
    User.objects.using(alias).filter(id=MACHINE_ID).update(is_active=False)
    Permission = apps.get_model("core", "Permission")
    for code in ("mcp.query", "service.integrate"):
        permission = Permission.objects.using(alias).filter(codename=code).first()
        if permission:
            permission.roles.clear()

class Migration(migrations.Migration):
    dependencies = [("core", "0002_attempt_foundation")]
    operations = [migrations.RunPython(forwards, backwards)]
