# Generated by Django 6.0.8 on 2026-09-10 18:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rbac_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('max_upload_bytes', models.PositiveBigIntegerField(default=26214400)),
                ('storage_quota_bytes', models.PositiveBigIntegerField(default=262144000)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('max_upload_bytes__gt', 0)), name='plan_positive_upload'), models.CheckConstraint(condition=models.Q(('storage_quota_bytes__gte', models.F('max_upload_bytes'))), name='plan_quota_covers_upload')],
            },
        ),
        migrations.CreateModel(
            name='UploadPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('max_upload_bytes', models.PositiveBigIntegerField(default=26214400)),
                ('default_storage_quota_bytes', models.PositiveBigIntegerField(default=262144000)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='upload_policy_singleton'), models.CheckConstraint(condition=models.Q(('max_upload_bytes__gt', 0)), name='policy_positive_upload'), models.CheckConstraint(condition=models.Q(('default_storage_quota_bytes__gte', models.F('max_upload_bytes'))), name='policy_quota_covers_upload')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('suspended', 'Suspensa'), ('expired', 'Expirada')], default='active', max_length=16)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plan')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='enrollment_valid_interval'), models.CheckConstraint(condition=models.Q(('status__in', ['active', 'suspended', 'expired'])), name='enrollment_valid_status')],
            },
        ),
    ]
