# Generated by Django 6.0.8 on 2026-09-10 18:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_upload_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserImportReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_key', models.CharField(max_length=64)),
                ('source_hash', models.CharField(max_length=64)),
                ('source_data', models.JSONField()),
                ('status', models.CharField(default='staged_unverified', max_length=32)),
                ('result', models.JSONField(default=dict)),
                ('provenance', models.CharField(default='authenticated_browser_export', max_length=80)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'source_key', 'source_hash'), name='browser_import_owner_source'), models.CheckConstraint(condition=models.Q(('status__in', ['staged_unverified', 'imported_personal'])), name='browser_import_status')],
            },
        ),
        migrations.CreateModel(
            name='StudyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_key', models.CharField(max_length=96)),
                ('kind', models.CharField(max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('payload_hash', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', '-occurred_at'], name='study_activity_owner_time')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'event_key'), name='study_activity_owner_event'), models.CheckConstraint(condition=models.Q(('kind__in', ('reading', 'review', 'practice', 'pomodoro'))), name='study_activity_kind'), models.CheckConstraint(condition=models.Q(('duration_seconds__lte', 86400)), name='study_activity_duration')],
            },
        ),
        migrations.CreateModel(
            name='StudyMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_kind', models.CharField(max_length=32)),
                ('target_id', models.UUIDField()),
                ('locator', models.CharField(max_length=512)),
                ('kind', models.CharField(max_length=20)),
                ('annotation', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'target_kind', 'target_id', 'locator', 'kind'), name='study_mark_owner_location'), models.CheckConstraint(condition=models.Q(('kind__in', ('highlight', 'review', 'question', 'memorize', 'exam'))), name='study_mark_kind'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='study_mark_version'), models.CheckConstraint(condition=models.Q(('target_kind__in', ('content', 'question', 'topic', 'document_version'))), name='study_mark_target_kind')],
            },
        ),
        migrations.CreateModel(
            name='StudyPanelState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_panel', models.CharField(default='dashboard', max_length=64)),
                ('pomodoro_status', models.CharField(default='idle', max_length=12)),
                ('remaining_seconds', models.PositiveIntegerField(default=1500)),
                ('timer_updated_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_panel_state', to=settings.AUTH_USER_MODEL)),
                ('study_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.studysession')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('pomodoro_status__in', ['idle', 'running', 'paused'])), name='study_panel_timer_state'), models.CheckConstraint(condition=models.Q(('remaining_seconds__lte', 86400)), name='study_panel_timer_limit'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='study_panel_version')],
            },
        ),
        migrations.CreateModel(
            name='StudyProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_kind', models.CharField(max_length=32)),
                ('target_id', models.UUIDField()),
                ('percent', models.PositiveSmallIntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'target_kind', 'target_id'), name='study_progress_owner_target'), models.CheckConstraint(condition=models.Q(('percent__lte', 100)), name='study_progress_percent'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='study_progress_version'), models.CheckConstraint(condition=models.Q(('target_kind__in', ('content', 'question', 'topic', 'document_version'))), name='study_progress_target_kind')],
            },
        ),
    ]
