# Generated by Django 6.0.8 on 2026-09-10 18:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_study_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em revisão'), ('approved', 'Aprovado'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='LegacyContentImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.CharField(max_length=32)),
                ('source_sha256', models.CharField(max_length=64)),
                ('preview_sha256', models.CharField(max_length=64)),
                ('item_count', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('preview', 'preview'), ('confirmed', 'confirmed')], default='preview', max_length=16)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_content_imports', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='LegacyContentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_sha256', models.CharField(max_length=64)),
                ('item_sha256', models.CharField(max_length=64)),
                ('locator', models.CharField(max_length=200)),
                ('legal_status', models.CharField(default='legacy_unverified', editable=False, max_length=32)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.legacycontentimport')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_import_item', to='core.contentversion')),
            ],
        ),
        migrations.CreateModel(
            name='ContentWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('draft', 'draft'), ('review', 'review'), ('approved', 'approved'), ('published', 'published'), ('archived', 'archived')], default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('approval', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_workflow', to='core.publicationapproval')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_workflows', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_workflows', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_workflows', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_workflows', to=settings.AUTH_USER_MODEL)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='workflow', to='core.contentversion')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['draft', 'review', 'approved', 'published', 'archived'])), name='content_workflow_valid_state'), models.CheckConstraint(condition=models.Q(models.Q(('state__in', ['approved', 'published']), _negated=True), ('approval__isnull', False), _connector='OR'), name='content_workflow_approval_required'), models.CheckConstraint(condition=models.Q(models.Q(('state', 'published'), _negated=True), models.Q(('published_at__isnull', False), ('published_by__isnull', False)), _connector='OR'), name='content_workflow_publisher_required')],
            },
        ),
        migrations.AddConstraint(
            model_name='legacycontentimport',
            constraint=models.UniqueConstraint(fields=('actor', 'preview_sha256'), name='legacy_content_actor_preview_unique'),
        ),
        migrations.AddConstraint(
            model_name='legacycontentitem',
            constraint=models.UniqueConstraint(fields=('source_sha256', 'item_sha256'), name='legacy_content_source_item_unique'),
        ),
    ]
