# Generated by Django 6.0.8 on 2026-09-10 23:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_content_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Intermediária'), ('hard', 'Difícil')], max_length=12)),
                ('origin', models.CharField(choices=[('official', 'Oficial'), ('authored', 'Autoral'), ('adapted', 'Adaptada')], max_length=16)),
                ('legal_basis', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('annulled', models.BooleanField(default=False)),
                ('answer_changed', models.BooleanField(default=False)),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_subtopics', to='core.topic')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='metadata', to='core.questionversion')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('difficulty__in', ['easy', 'medium', 'hard'])), name='question_metadata_difficulty'), models.CheckConstraint(condition=models.Q(('origin__in', ['official', 'authored', 'adapted'])), name='question_metadata_origin')],
            },
        ),
        migrations.CreateModel(
            name='QuestionWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em revisão'), ('approved', 'Aprovado'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('answer_key_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='question_workflow', to='core.answerkeyversion')),
                ('approval', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_workflow', to='core.publicationapproval')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_questions', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_questions', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_questions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_questions', to=settings.AUTH_USER_MODEL)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='workflow', to='core.questionversion')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['draft', 'review', 'approved', 'published', 'archived'])), name='question_workflow_valid_state'), models.CheckConstraint(condition=models.Q(models.Q(('state__in', ['approved', 'published']), _negated=True), ('approval__isnull', False), _connector='OR'), name='question_workflow_approval_required'), models.CheckConstraint(condition=models.Q(models.Q(('state', 'published'), _negated=True), models.Q(('published_at__isnull', False), ('published_by__isnull', False)), _connector='OR'), name='question_workflow_publisher_required')],
            },
        ),
    ]
