# Generated by Django 6.0.8 on 2026-09-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_question_editorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='is_correct',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['question', 'is_correct'], name='question_answer_accuracy'),
        ),
    ]
