# Generated by Django 6.0.8 on 2026-09-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_objective_answer_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='selection_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
