# Generated by Django 6.0.8 on 2026-09-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_simulation_preparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='marked_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
