# Generated by Django 6.0.8 on 2026-09-11 00:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_attempt_review_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondPhaseArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RubricCriterionDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(max_length=120)),
                ('target_code', models.CharField(default='piece', max_length=32)),
                ('legal_basis', models.TextField(blank=True)),
                ('acceptable_answers', models.JSONField(default=list)),
                ('dependencies', models.JSONField(default=list)),
                ('required', models.BooleanField(default=False)),
                ('criterion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='core.rubriccriterion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WrittenCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('provenance', models.JSONField(default=dict)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WrittenCorrectionReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('correction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='core.writtencorrection')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('successor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supersedes_review', to='core.writtencorrection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WrittenSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('formal', 'Formal'), ('training', 'Treino')], max_length=12)),
                ('status', models.CharField(choices=[('active', 'Em andamento'), ('submitted', 'Enviada')], default='active', max_length=12)),
                ('request_id', models.UUIDField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('elapsed_seconds', models.PositiveIntegerField(default=0)),
                ('frozen_definition', models.JSONField()),
                ('final_hash', models.CharField(blank=True, max_length=64)),
                ('case_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='written_submissions', to='core.practicalcaseversion')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='written_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WrittenResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_code', models.CharField(max_length=32)),
                ('text', models.TextField(blank=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='core.writtensubmission')),
            ],
        ),
        migrations.AddField(
            model_name='writtencorrection',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='core.writtensubmission'),
        ),
        migrations.CreateModel(
            name='WrittenCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkpoints', to='core.writtensubmission')),
            ],
        ),
        migrations.CreateModel(
            name='DiscursiveQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('prompt', models.TextField()),
                ('expected_answer', models.TextField()),
                ('order', models.PositiveSmallIntegerField()),
                ('case_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discursive_questions', to='core.practicalcaseversion')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('case_version', 'code'), name='phase2_unique_discursive_code'), models.UniqueConstraint(fields=('case_version', 'order'), name='phase2_unique_discursive_order')],
            },
        ),
        migrations.CreateModel(
            name='SecondPhaseCaseMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('piece_name', models.CharField(max_length=200)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=300)),
                ('provenance', models.CharField(choices=[('human_authored', 'Autoral'), ('official', 'Oficial'), ('legacy_unverified', 'Legado não verificado')], default='human_authored', max_length=32)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.secondphasearea')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='educational_metadata', to='core.practicalcaseversion')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 1), ('duration_minutes__lte', 1440)), name='phase2_duration_range'), models.CheckConstraint(condition=models.Q(('provenance__in', ['human_authored', 'official', 'legacy_unverified'])), name='phase2_valid_provenance')],
            },
        ),
        migrations.CreateModel(
            name='SecondPhaseWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em revisão'), ('approved', 'Aprovado'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('approval', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phase2_workflow', to='core.publicationapproval')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_phase2', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_phase2', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_phase2', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_phase2', to=settings.AUTH_USER_MODEL)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='editorial_workflow', to='core.practicalcaseversion')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['draft', 'review', 'approved', 'published', 'archived'])), name='phase2_workflow_state'), models.CheckConstraint(condition=models.Q(models.Q(('state__in', ['approved', 'published']), _negated=True), ('approval__isnull', False), _connector='OR'), name='phase2_requires_approval'), models.CheckConstraint(condition=models.Q(models.Q(('state', 'published'), _negated=True), models.Q(('published_at__isnull', False), ('published_by__isnull', False)), _connector='OR'), name='phase2_requires_publisher')],
            },
        ),
        migrations.CreateModel(
            name='WrittenCorrectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('evidence_text', models.TextField(blank=True)),
                ('justification', models.TextField()),
                ('legal_basis', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('observation', models.TextField(blank=True)),
                ('correction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.writtencorrection')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rubriccriterion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('correction', 'criterion'), name='phase2_correction_criterion'), models.CheckConstraint(condition=models.Q(('max_points__gte', 0), ('points__gte', 0), ('points__lte', models.F('max_points'))), name='phase2_correction_item_range'), models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='phase2_correction_confidence')],
            },
        ),
        migrations.AddIndex(
            model_name='writtensubmission',
            index=models.Index(fields=['owner', 'status', '-started_at'], name='phase2_owner_status_started'),
        ),
        migrations.AddConstraint(
            model_name='writtensubmission',
            constraint=models.UniqueConstraint(fields=('owner', 'request_id'), name='phase2_owner_request'),
        ),
        migrations.AddConstraint(
            model_name='writtensubmission',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='phase2_submission_version'),
        ),
        migrations.AddConstraint(
            model_name='writtensubmission',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ['formal', 'training'])), name='phase2_submission_mode'),
        ),
        migrations.AddConstraint(
            model_name='writtensubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('final_hash', ''), ('status', 'active'), ('submitted_at__isnull', True)), models.Q(('status', 'submitted'), ('submitted_at__isnull', False), models.Q(('final_hash', ''), _negated=True)), _connector='OR'), name='phase2_submission_state'),
        ),
        migrations.AddConstraint(
            model_name='writtenresponse',
            constraint=models.UniqueConstraint(fields=('submission', 'target_code'), name='phase2_response_target'),
        ),
        migrations.AddConstraint(
            model_name='writtencorrection',
            constraint=models.UniqueConstraint(fields=('submission', 'version'), name='phase2_correction_version'),
        ),
        migrations.AddConstraint(
            model_name='writtencorrection',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0), ('total_score__gte', 0), ('total_score__lte', models.F('max_score'))), name='phase2_correction_score_range'),
        ),
        migrations.AddConstraint(
            model_name='writtencheckpoint',
            constraint=models.UniqueConstraint(fields=('submission', 'version'), name='phase2_checkpoint_version'),
        ),
    ]
