# Generated by Django 6.0.8 on 2026-09-11 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_second_phase_written_exams'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogress',
            name='content_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='study_progress', to='core.contentversion'),
        ),
        migrations.AddConstraint(
            model_name='studyprogress',
            constraint=models.CheckConstraint(condition=models.Q(('content_version__isnull', True), ('target_kind', 'content'), _connector='OR'), name='study_progress_content_version_kind'),
        ),
    ]
