# Generated by Django 6.0.8 on 2026-09-11 01:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_reading_version_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percent', models.PositiveSmallIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField()),
                ('content_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reading_history', to='core.contentversion')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'content_version'), name='reading_history_owner_version'), models.CheckConstraint(condition=models.Q(('percent__lte', 100)), name='reading_history_percent')],
            },
        ),
    ]
