# Generated by Django 6.0.8 on 2026-09-11 01:53

import django.db.models.functions.text
from django.db import migrations, models


def check_recovery_addresses(apps, schema_editor):
    User = apps.get_model("core", "User")
    duplicates = User.objects.using(schema_editor.connection.alias).exclude(email="").annotate(address=django.db.models.functions.text.Lower("email")).values("address").annotate(total=models.Count("pk")).filter(total__gt=1)
    if duplicates.exists():
        raise RuntimeError("Recovery email collisions require an authorized review before migration; no address or account data was changed.")


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0013_reading_history'),
    ]

    operations = [
        migrations.RunPython(check_recovery_addresses, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='user_email_unique_ci'),
        ),
    ]
