# Generated by Django 6.0.8 on 2026-09-11 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_unique_recovery_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studynote',
            name='content_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_notes', to='core.contentversion'),
        ),
        migrations.AddField(
            model_name='studynote',
            name='creation_key',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='studynote',
            name='creation_payload_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='studynote',
            constraint=models.UniqueConstraint(condition=models.Q(('creation_key__isnull', False)), fields=('owner', 'creation_key'), name='note_owner_creation_key'),
        ),
        migrations.AddConstraint(
            model_name='studynote',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='note_positive_version'),
        ),
    ]
