# Generated by Django 6.0.8 on 2026-09-11 05:53

from django.db import migrations, models


def preserve_last_review_schedule(apps, schema_editor):
    Card = apps.get_model('core', 'Flashcard')
    Review = apps.get_model('core', 'FlashcardReview')
    last = Review.objects.using(schema_editor.connection.alias).filter(
        flashcard_id=models.OuterRef('pk'), owner_id=models.OuterRef('owner_id')
    ).order_by('-reviewed_at', '-pk').values('next_review_at')[:1]
    Card.objects.using(schema_editor.connection.alias).update(next_review_at=models.Subquery(last))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_personal_note_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='creation_key',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='creation_payload_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='next_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flashcardreview',
            name='card_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flashcardreview',
            name='idempotency_key',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='flashcardreview',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(preserve_last_review_schedule, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['owner', 'archived_at', 'next_review_at'], name='card_owner_review_due'),
        ),
        migrations.AddConstraint(
            model_name='flashcard',
            constraint=models.UniqueConstraint(condition=models.Q(('creation_key__isnull', False)), fields=('owner', 'creation_key'), name='card_owner_creation_key'),
        ),
        migrations.AddConstraint(
            model_name='flashcard',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='card_positive_version'),
        ),
        migrations.AddConstraint(
            model_name='flashcardreview',
            constraint=models.CheckConstraint(condition=models.Q(('card_version__gte', 1)), name='review_positive_card_version'),
        ),
        migrations.AddConstraint(
            model_name='flashcardreview',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('owner', 'idempotency_key'), name='card_review_owner_key'),
        ),
    ]
