# Generated by Django 6.0.8 on 2026-09-11 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_personal_flashcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='creation_key',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='creation_payload_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='goal',
            name='metric',
            field=models.CharField(choices=[('manual', 'Conclusão manual'), ('questions', 'Questões respondidas'), ('study_minutes', 'Minutos de estudo registrados'), ('simulations', 'Simulados concluídos'), ('flashcard_reviews', 'Revisões de flashcards')], default='manual', max_length=24),
        ),
        migrations.AddField(
            model_name='goal',
            name='priority',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='goal',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.subject'),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('metric__in', ['manual', 'questions', 'study_minutes', 'simulations', 'flashcard_reviews'])), name='goal_valid_metric'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('metric', 'manual'), models.Q(('completed_at__isnull', True), ('progress', 0), ('start_date__isnull', False), ('target_date__isnull', False), ('target_value__gte', 1), ('target_value__isnull', False), ('target_value__lte', 100000), ('target_date__gte', models.F('start_date'))), _connector='OR'), name='goal_quantitative_shape'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('subject__isnull', True), ('metric', 'questions'), _connector='OR'), name='goal_subject_questions_only'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gte', 1), ('priority__lte', 3)), name='goal_priority_range'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='goal_positive_version'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.UniqueConstraint(condition=models.Q(('creation_key__isnull', False)), fields=('owner', 'creation_key'), name='goal_owner_creation_key'),
        ),
    ]
