#!/usr/bin/env python3
"""Strict release gate with explicitly reviewed Kairós configuration hash changes."""

import argparse
import hashlib
import json
from pathlib import Path, PurePosixPath
import re
import subprocess
import sys

REQUIRED = (
    "containers.txt",
    "container-identities.txt",
    "networks.txt",
    "volumes.txt",
    "images.txt",
    "listeners.txt",
    "services-running.txt",
    "nginx-config-hashes.txt",
    "compose-config-hashes.txt",
    "cron-hashes.txt",
    "public-certificate-hashes.txt",
    "iptables.txt",
    "ip6tables.txt",
    "nft-ruleset.txt",
)
HASH_FILES = (
    "nginx-config-hashes.txt",
    "compose-config-hashes.txt",
    "release-config-hashes.txt",
)
OWN_NAME = re.compile(r"^/?kairos(?:[-_]|$)")
SHA = re.compile(r"[a-f0-9]{64}")


class GateError(Exception):
    pass


def read(path):
    if path.is_symlink() or not path.is_file() or path.stat().st_size > 16 * 1024**2:
        raise GateError("missing_or_invalid_inventory:" + path.name)
    return path.read_text(encoding="utf-8")


def kairos_path(value):
    if (
        not isinstance(value, str)
        or any(ord(c) < 32 for c in value)
        or any(c in value for c in "*?[]\\")
    ):
        return False
    path = PurePosixPath(value)
    if not path.is_absolute() or str(path) != value or ".." in path.parts:
        return False
    if path.name.startswith(".env") or "/secrets/" in value:
        return False
    if value.startswith("/opt/kairos/current/infra/"):
        return True
    if re.fullmatch(
        r"/opt/kairos/(?:releases/[a-f0-9]{40}|runtime/[A-Za-z0-9_./-]+)/[^\r\n]*",
        value,
    ):
        return "/infra/" in value and "/secrets/" not in value
    if value in {
        "/etc/nginx/sites-available/kairos-sslip.conf",
        "/etc/nginx/sites-enabled/kairos-sslip.conf",
    }:
        return True
    return bool(
        re.fullmatch(r"/etc/systemd/system/kairos-[a-z0-9-]+\.(?:service|timer)", value)
    )


def manifest_changes(manifest):
    if (
        not isinstance(manifest, dict)
        or set(manifest) != {"version", "release_commit", "config_changes"}
        or manifest["version"] != 1
    ):
        raise GateError("invalid_manifest_schema")
    if not re.fullmatch(r"[a-f0-9]{40}", manifest["release_commit"]):
        raise GateError("invalid_release_commit")
    if not isinstance(manifest["config_changes"], list):
        raise GateError("invalid_config_changes")
    result = {}
    for item in manifest["config_changes"]:
        if not isinstance(item, dict) or set(item) != {"path", "before", "after"}:
            raise GateError("invalid_config_change")
        path, before, after = item["path"], item["before"], item["after"]
        if not kairos_path(path) or path in result:
            raise GateError("non_kairos_or_duplicate_config_path")
        if before is not None and (
            not isinstance(before, str) or not SHA.fullmatch(before)
        ):
            raise GateError("invalid_before_hash")
        if not isinstance(after, str) or not SHA.fullmatch(after) or before == after:
            raise GateError("invalid_after_hash")
        result[path] = (before, after)
    return result


def hashes(text):
    result = {}
    for line in text.splitlines():
        match = re.fullmatch(r"([a-f0-9]{64})  (/[^\r\n]+)", line)
        if not match or match[2] in result:
            raise GateError("malformed_hash_inventory")
        result[match[2]] = match[1]
    return result


def foreign_rows(text, column=1):
    rows = []
    for line in text.splitlines():
        parts = line.split("|")
        if len(parts) <= column:
            raise GateError("malformed_resource_inventory")
        if not OWN_NAME.match(parts[column]):
            rows.append(line)
    return sorted(rows)


def normalized_firewall(text, nft=False):
    result = []
    for line in text.splitlines():
        if not nft and re.match(r"^# (Generated by|Completed on)", line):
            continue
        if nft:
            line = re.sub(
                r"counter packets \d+ bytes \d+",
                "counter packets COUNTER bytes COUNTER",
                line,
            )
        else:
            line = re.sub(r"\[\d+:\d+\]", "[COUNTERS]", line)
            line = re.sub(r"-c \d+ \d+", "-c COUNTER COUNTER", line)
        result.append(line)
    # Firewall order is significant. Do not sort, deduplicate or remove shared chains.
    return result


def compare(before, after, manifest):
    before, after = Path(before), Path(after)
    permitted = manifest_changes(manifest)
    inventories = {}
    for name in REQUIRED:
        inventories[name] = (read(before / name), read(after / name))
    if (before / "release-config-hashes.txt").exists() or (
        after / "release-config-hashes.txt"
    ).exists():
        inventories["release-config-hashes.txt"] = (
            read(before / "release-config-hashes.txt"),
            read(after / "release-config-hashes.txt"),
        )
    failures = []
    observed = {}
    all_hashes = [{}, {}]
    for name in HASH_FILES:
        if name not in inventories:
            continue
        pairs = [hashes(text) for text in inventories[name]]
        for side, values in enumerate(pairs):
            for path, digest in values.items():
                if path in all_hashes[side] and all_hashes[side][path] != digest:
                    raise GateError("inconsistent_cross_inventory_hash")
                all_hashes[side][path] = digest
        for path in pairs[0].keys() | pairs[1].keys():
            difference = (pairs[0].get(path), pairs[1].get(path))
            if difference[0] == difference[1]:
                continue
            if permitted.get(path) != difference:
                failures.append(name + ":unauthorized_config_difference")
            observed[path] = difference
    for path, expected in permitted.items():
        if (
            all_hashes[0].get(path),
            all_hashes[1].get(path),
        ) != expected or path not in observed:
            failures.append("manifest:unobserved_or_wrong_expected_change")

    for name in ("containers.txt", "container-identities.txt", "networks.txt"):
        if foreign_rows(inventories[name][0]) != foreign_rows(inventories[name][1]):
            failures.append(name + ":unrelated_identity_changed")
    for name in ("volumes.txt", "images.txt"):
        # Preserve every old resource; additive Kairós build artifacts are checked by release inventory.
        if not set(inventories[name][0].splitlines()).issubset(
            inventories[name][1].splitlines()
        ):
            failures.append(name + ":preexisting_resource_removed")
    for name in ("listeners.txt", "cron-hashes.txt", "public-certificate-hashes.txt"):
        if sorted(inventories[name][0].splitlines()) != sorted(
            inventories[name][1].splitlines()
        ):
            failures.append(name + ":strict_difference")
    if foreign_rows(inventories["services-running.txt"][0], 0) != foreign_rows(
        inventories["services-running.txt"][1], 0
    ):
        failures.append("services-running.txt:unrelated_service_changed")
    for name in ("iptables.txt", "ip6tables.txt", "nft-ruleset.txt"):
        pair = inventories[name]
        if normalized_firewall(
            pair[0], name == "nft-ruleset.txt"
        ) != normalized_firewall(pair[1], name == "nft-ruleset.txt"):
            failures.append(name + ":strict_firewall_difference")
    # Ownership projection is supplementary evidence, never permission to omit firewall rules.
    ownership_name = "network-ownership.json"
    if (before / ownership_name).exists() or (after / ownership_name).exists():
        projections = [
            json.loads(read(folder / ownership_name)) for folder in (before, after)
        ]
        for key in ("containers", "networks"):
            foreign = []
            for projection in projections:
                if projection.get("version") != 1 or not isinstance(
                    projection.get(key), list
                ):
                    raise GateError("invalid_network_ownership")
                owned_container_ids = {
                    row.get("id")
                    for row in projection.get("containers", [])
                    if row.get("project") == "kairos"
                    and OWN_NAME.match(row.get("name", ""))
                }
                foreign.append(
                    sorted(
                        json.dumps(row, sort_keys=True)
                        for row in projection[key]
                        if row.get("project") != "kairos"
                        or not OWN_NAME.match(row.get("name", ""))
                        or (
                            key == "networks"
                            and any(
                                item.get("id") not in owned_container_ids
                                for item in row.get("containers", [])
                            )
                        )
                    )
                )
            if foreign[0] != foreign[1]:
                failures.append(ownership_name + ":unrelated_" + key + "_changed")
    return {
        "result": "FAIL" if failures else "PASS",
        "phase": "configuration_exceptions_only",
        "release_commit": manifest["release_commit"],
        "authorized_config_changes": len(permitted),
        "failures": sorted(set(failures)),
        "firewall_exceptions": False,
        "listener_exceptions": False,
    }


def run(before, after, manifest_path=None, legacy_runner=subprocess.run):
    if manifest_path is None:
        return legacy_runner(
            [
                "bash",
                str(Path(__file__).with_name("compare-vps-snapshots.sh")),
                str(before),
                str(after),
            ],
            check=False,
        ).returncode
    data = read(Path(manifest_path))
    result = compare(before, after, json.loads(data))
    result["manifest_sha256"] = hashlib.sha256(data.encode()).hexdigest()
    print(json.dumps(result, sort_keys=True))
    return 0 if result["result"] == "PASS" else 1


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("before")
    parser.add_argument("after")
    parser.add_argument("--manifest")
    args = parser.parse_args()
    try:
        sys.exit(run(args.before, args.after, args.manifest))
    except Exception as exc:
        print(json.dumps({"result": "FAIL", "error": type(exc).__name__}))
        sys.exit(1)
