const assert = require('node:assert/strict');
const {join} = require('node:path');
const {writeFile} = require('node:fs/promises');

module.exports = async function flashcards(page, context, origin, evidence, expectLost) {
  page.setDefaultTimeout(12000); page.setDefaultNavigationTimeout(15000);
  let step = 0;
  const mark = async stage => writeFile(join(evidence, 'flashcards-progress.json'), JSON.stringify({stage, step: ++step, forms: await page.locator('.flashcards-workspace form').count(), inputs: await page.getByLabel('Pergunta', {exact: true}).count(), status: await page.locator('[role="status"]').allTextContents()}));
  await mark('opening');
  await page.goto(origin + '/app/biblioteca?aba=flashcards');
  await mark('opened');
  await page.getByLabel('Pergunta', {exact: true}).fill('Pergunta pessoal para revisão espaçada');
  await page.getByLabel('Resposta', {exact: true}).fill('Resposta pessoal <img src=x onerror=alert(1)>\n  ');
  await page.getByLabel('Referência pessoal', {exact: true}).fill('Fonte pessoal ainda não verificada.');
  assert.equal(await page.getByRole('button', {name: 'Leituras publicadas', exact: true}).isDisabled(), true);
  await mark('before-loss');
  expectLost();
  await page.route('**/api/flashcards/', async route => {
    if (route.request().method() !== 'POST') return route.continue();
    const response = await route.fetch(); assert.equal(response.status(), 201); await route.abort('failed');
  }, {times: 1});
  await mark('before-save');
  await page.getByRole('button', {name: 'Salvar cartão', exact: true}).click();
  await mark('save-clicked');
  await page.getByText('Confira o salvamento antes de repetir.', {exact: false}).waitFor();
  page.once('dialog', dialog => dialog.accept());
  await mark('before-reload');
  await page.reload();
  await mark('reloaded');
  await mark('before-reconcile');
  await page.getByRole('button', {name: 'Conferir salvamento ou revisão', exact: true}).click();
  await mark('reconciled-clicked');
  await page.getByText('Salvamento confirmado no servidor.', {exact: true}).waitFor();
  let list = await (await context.request.get(origin + '/api/flashcards/?mode=all')).json();
  assert.equal(list.count, 1); const id = list.results[0].id;
  await page.getByRole('button', {name: 'Revelar resposta', exact: true}).focus();
  await page.keyboard.press('Enter');
  assert.equal(await page.locator('.flashcard-answer img').count(), 0);
  await mark('before-loss');
  expectLost();
  await page.route(`**/api/flashcards/${id}/review/`, async route => {
    const response = await route.fetch(); assert.equal(response.status(), 200); await route.abort('failed');
  }, {times: 1});
  await page.getByRole('button', {name: 'Razoável · 3 dias', exact: true}).click();
  await page.getByText('Confira a revisão antes de enviar outra avaliação.', {exact: false}).waitFor();
  page.once('dialog', dialog => dialog.accept());
  await mark('before-reload');
  await page.reload();
  await mark('reloaded');
  await mark('before-reconcile');
  await page.getByRole('button', {name: 'Conferir salvamento ou revisão', exact: true}).click();
  await mark('reconciled-clicked');
  await page.getByText('Revisão confirmada uma única vez.', {exact: false}).waitFor();
  let history = await (await context.request.get(origin + `/api/flashcards/${id}/history/`)).json();
  assert.equal(history.count, 1); assert.equal(history.results[0].rating, 3);
  assert.equal((await (await context.request.get(origin + '/api/flashcards/?mode=due')).json()).count, 0);
  await page.getByRole('button', {name: 'Editar cartão', exact: true}).click();
  await mark('edit-clicked');
  await page.getByLabel('Pergunta', {exact: true}).fill('Pergunta pessoal revisada e persistida');
  await mark('before-loss');
  expectLost();
  await page.route(`**/api/flashcards/${id}/`, async route => {
    const response = await route.fetch(); assert.equal(response.status(), 200); await route.abort('failed');
  }, {times: 1});
  await mark('before-save');
  await page.getByRole('button', {name: 'Salvar cartão', exact: true}).click();
  await mark('save-clicked');
  await page.getByText('Confira o salvamento antes de repetir.', {exact: false}).waitFor();
  await mark('before-reconcile');
  await page.getByRole('button', {name: 'Conferir salvamento ou revisão', exact: true}).click();
  await mark('reconciled-clicked');
  await page.getByText('Salvamento confirmado no servidor.', {exact: true}).waitFor();
  await page.getByRole('button', {name: 'Editar cartão', exact: true}).click();
  await mark('edit-clicked');
  await page.getByLabel('Resposta', {exact: true}).fill('Rascunho ainda não enviado, preservado após refresh.');
  await page.evaluate(() => window.history.pushState(null, '', '?aba=leituras'));
  await page.getByRole('button', {name: 'Meus flashcards', exact: true}).click();
  await page.getByRole('button', {name: 'Conferir salvamento ou revisão', exact: true}).waitFor();
  assert.equal(await page.getByLabel('Resposta', {exact: true}).inputValue(), 'Rascunho ainda não enviado, preservado após refresh.');
  page.once('dialog', dialog => dialog.accept());
  await mark('before-reload');
  await page.reload();
  await mark('reloaded');
  await mark('before-reconcile');
  await page.getByRole('button', {name: 'Conferir salvamento ou revisão', exact: true}).click();
  await mark('reconciled-clicked');
  await page.getByText('O rascunho ainda não está salvo.', {exact: false}).waitFor();
  assert.equal(await page.getByLabel('Resposta', {exact: true}).inputValue(), 'Rascunho ainda não enviado, preservado após refresh.');
  await mark('before-save');
  await page.getByRole('button', {name: 'Salvar cartão', exact: true}).click();
  await mark('save-clicked');
  await page.getByText('Cartão salvo na sua conta.', {exact: true}).waitFor();
  await page.getByRole('button', {name: 'Editar cartão', exact: true}).click();
  await page.getByLabel('Resposta', {exact: true}).fill('Meu texto mantido após comparar a alteração de outra aba.');
  const csrf = await (await context.request.get(origin + '/api/auth/csrf')).json();
  const concurrent = await context.request.patch(origin + `/api/flashcards/${id}/`, {data: {front: 'Texto salvo por outra aba', expected_version: 4}, headers: {'X-CSRFToken': csrf.csrfToken}});
  assert.equal(concurrent.status(), 200);
  expectLost('conflict');
  await page.getByRole('button', {name: 'Salvar cartão', exact: true}).click();
  await page.getByText('Confira o salvamento antes de repetir.', {exact: false}).waitFor();
  await page.getByRole('button', {name: 'Conferir salvamento ou revisão', exact: true}).click();
  await page.getByRole('region', {name: 'Comparar cartão salvo', exact: true}).getByText('Texto salvo por outra aba', {exact: true}).waitFor();
  await page.getByRole('button', {name: 'Manter meu texto em edição', exact: true}).click();
  assert.equal(await page.getByLabel('Resposta', {exact: true}).inputValue(), 'Meu texto mantido após comparar a alteração de outra aba.');
  await page.getByRole('button', {name: 'Salvar cartão', exact: true}).click();
  await page.getByText('Cartão salvo na sua conta.', {exact: true}).waitFor();
  await page.getByRole('button', {name: 'Revelar resposta', exact: true}).click();
  await page.getByRole('button', {name: 'Histórico de revisões', exact: true}).click();
  await page.getByRole('region', {name: 'Histórico de revisões', exact: true}).waitFor();
  await page.locator('.flashcards-workspace details summary').click();
  await page.getByText('Pergunta pessoal para revisão espaçada', {exact: true}).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.evaluate(() => window.scrollTo({top: 0, behavior: 'instant'}));
  await page.screenshot({path: join(evidence, 'flashcards-mobile.png'), fullPage: true});
  for (const width of [768, 1440]) {
    await page.setViewportSize({width, height: 1000});
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  }
  await page.setViewportSize({width: 390, height: 844});
  await page.getByRole('button', {name: 'Arquivar cartão', exact: true}).click();
  await page.getByText('Situação do cartão atualizada.', {exact: false}).waitFor();
  await page.getByLabel('Exibir', {exact: true}).selectOption('archived');
  await page.getByRole('button', {name: 'Filtrar cartões', exact: true}).click();
  await page.locator('.flashcards-workspace .open-row').getByText('Pergunta pessoal revisada e persistida', {exact: true}).waitFor();
  await page.getByRole('button', {name: 'Reativar cartão', exact: true}).click();
  await page.getByRole('button', {name: 'Arquivar cartão', exact: true}).waitFor();
  list = await (await context.request.get(origin + '/api/flashcards/?mode=all')).json();
  history = await (await context.request.get(origin + `/api/flashcards/${id}/history/`)).json();
  assert.equal(list.count, 1); assert.equal(list.results[0].version, 8); assert.equal(history.count, 1);
  assert.equal(history.results[0].snapshot.front, 'Pergunta pessoal para revisão espaçada');
  return 'create-lost-response-refresh-review-replay-edit-draft-archive-history-mobile PASS';
};
